


const LogGroupName = {
    ForensicLogTemplate: "ForensicLog Template"
}
const LogSubGroupName = {
    Auth: "Auth",
    Ap: "AP",
    Entity: "Entity",
    ApProfile: "ApProfile",
    DataCenterHierarchy: "DataCenterHierarchy",
    InventoryStoreandBins: "InventoryStoreandBins",
    Entities: "Entities",
    AppQatask: "AppQatask",
    Device: "Device",
    DeviceModel: "DeviceModel",
    Audit: "Audit",
    InventoryReconciliation: "InventoryReconciliation",
    Filter: "Filter",
    Cabling: "Cabling",
    Help: "Help",
    KebabMenu: "KebabMenu"
}
const LogName = {
    LogIn: "Login",
    SignOut: "SignOut",
    AddUser: "AddUser",
    UpdateUser: "UpdateUser",
    DeleteUser: "DeleteUser",
    AddRole: "AddRole",
    UpdateRole: "UpdateRole",
    DeleteRole: "DeleteRole",
    AddLicense: "AddLicense",
    UpdateLicense: "UpdateLicense",
    DeleteLicense: "DeleteLicense",
    AddTeam: "AddTeam",
    UpdateTeam: "UpdateTeam",
    DeleteTeam: "DeleteTeam",
    AssignEntity: "AssignEntity",
    AuthorizeEntities: "AuthorizeEntities",
    AuthorizeFeatures: "AuthorizeFeatures",
    Authorize: "Authorize",
    DelegateToAnotherUser: "DelegateToAnotherUser",
    UpdateValue: "UpdateValue",
    AddEntity: "AddEntity",
    UpdateEntity: "UpdateEntity",
    DeleteEntity: "DeleteEntity",
    AddAPProfile: "AddAPProfile",
    UpdateAPProfile: "UpdateAPProfile",
    DeleteAPProfile: "DeleteAPProfile",
    EmptyEntity: "EmptyEntity",
    Import: "Import",
    task: "task",
    taskDelete: "taskDelete",
    Delete: "Delete",
    Empty: "Empty",
    Move: "Move",
    AddDevice: "AddDevice",
    Add: "Add",
    StatusChange: "StatusChange",
    Snapshot: "Snapshot",
    Status: "Status",
    ChangeSite: "ChangeSite",
    DeleteConnection: "DeleteConnection",
    CreateConnection: "CreateConnection",
    DisconnectCable: "DisconnectCable",
    RemoteHelp: "RemoteHelp",
    DisposeAll: "DisposeAll",
    RemoteURL: "RemoteURL"
}
export { LogGroupName, LogSubGroupName, LogName }